### ISSUE TITLE
root

### ISSUE THREAD

**Issue by viewwinbaby** [yrshaikh/Code-Formatter#3]
/**
 * Invoked when the AdsLoader successfully fetched ads.
 */
private function adsManagerLoadedHandler(event:AdsManagerLoadedEvent):void {
  // Publishers can modify the default preferences through this object.
  var adsRenderingSettings:AdsRenderingSettings =
      new AdsRenderingSettings();

  // In order to support ad rules playlists, ads manager requires an object that
  // provides current playhead position for the content.
  var contentPlayhead:Object = {};
  contentPlayhead.time = function():Number {
    return contentPlayheadTime * 1000; // convert to milliseconds.
  };

  // Get a reference to the AdsManager object through the event object.
  adsManager = event.getAdsManager(contentPlayhead, adsRenderingSettings);
}

**Comment by yrshaikh** [comment]
whats this supposed to mean ?
