### ISSUE TITLE
It doesn't enough work for me

### ISSUE THREAD

**Issue by bayashi** [yrshaikh/Code-Formatter#4]
Thank you for nice addon!
Once I tried to beautified below JSON.

```
{"foo" => "bar","user" => {"name" => "baz"}}
```

I got below result.

```
{
    "foo" = > "bar", "user" = > {
        "name" = > "baz"
    }
}
```

Although I have expected below result.

```
{
    "foo"=>"bar",
    "user"=>{
        "name"=>"baz"
    }
}
```

Moreover, below CSS line.

```
#foo{color:#123456}.bar{color:#aabbcc}
```

I got below result.

```
#
foo {
    color: #123456}.bar{color:# aabbcc
}
```

I use Chrome 41.0.2272.89 m.
I'm glad to be fixed this issue. Thank you.

**Comment by yrshaikh** [comment]
Thanks for posting this issue.. Will check this issue over the weekend and try and get this resolved.
